FROM postgres:15-alpine

# Create directories for scripts and data
RUN mkdir -p /scripts/sql /docker-entrypoint-initdb.d

# Copy scripts, sql, and data into the container
COPY scripts/sql /docker-entrypoint-initdb.d
COPY scripts/data /docker-entrypoint-initdb.d
COPY scripts/init-data.sh /scripts/

# Set the correct permissions
RUN chmod -R 755 /scripts /docker-entrypoint-initdb.d

# Set the entrypoint to the script
CMD ["/scripts/init-data.sh"]
