FROM node:18-alpine

WORKDIR /usr/src/app

# Install the latest version of drizzle-orm
RUN npm install -g drizzle-orm@latest

# Install drizzle-kit
RUN npm install -g drizzle-kit@latest

EXPOSE 4983

CMD ["npx", "drizzle-kit", "studio", "--port", "4983", "--host", "0.0.0.0"]
