services:
  db:
    image: postgres:15-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env.development
    networks:
      - database
    ports:
      - "5432:5432"
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    init: true
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app
      - database
    depends_on:
      - db
    ports:
      - "3000:3000"
    env_file:
      - .env.development
  init-data:
    build:
      context: .
      dockerfile: docker/Dockerfile.init-data
    env_file:
      - .env.development
    networks:
      - database
    depends_on:
      - db
      - app
  drizzle-studio:
    build:
      context: .
      dockerfile: docker/Dockerfile.studio
    env_file:
      - .env.development
    ports:
      - "4983:4983"
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
      - app
    networks:
      - database

volumes:
  pgdata:
networks:
  database:
  app:
