FROM node:18-alpine

WORKDIR /usr/src/app

RUN npm install -g drizzle-orm@latest

RUN npm install -g drizzle-kit@latest

EXPOSE 4983

CMD ["npx", "drizzle-kit", "studio", "--port", "4983", "--host", "0.0.0.0"]
