FROM postgres:15-alpine

RUN mkdir -p /scripts/sql /docker-entrypoint-initdb.d

COPY scripts/sql /docker-entrypoint-initdb.d
COPY scripts/data /docker-entrypoint-initdb.d
COPY scripts/init-data.sh /scripts/

RUN chmod -R 755 /scripts /docker-entrypoint-initdb.d

CMD ["/scripts/init-data.sh"]
